### PR TITLE
feat: Add browser-sync

### PR DESCRIPTION
**Pull request by alexanderGugel**
@talves As discussed on Slack.

Adds optional live reloading.

### CODE REVIEW

**Comment by talves** [comment]
Unfortunately the `&` (parallel command) does not work on Windows

**Comment by TheAlphaNerd** [comment]
We are likely going to avoid introducing browser-sync

We have a fix coming in later today that will make windows work and get rid of the & operator

**Comment by michaelobriena** [comment]
Not a fan of this.  I don't think browser-sync is something we want as part of the seed as Myles mentioned.

**Comment by alexanderGugel** [comment]
Livereload was a requested feature on Slack. I think it's fair to say that we don't want our community to get RSI. We originally removed `browser-sync

**Comment by trusktr** [comment]
I like live reload. Maybe it's because I'm lazy? But oh well, I still like it. :D

**Comment by talves** [comment]
Of course, anyone has the choice to create their own seed and use any tool they need.  I don't see it as an issue leaving the solution the way it is.  The community will create alternative solutions.  They just will not be available through the Famous-CLI.

**Pull request closed without merging**
